# -*- coding: utf-8 -*-
"""formulario.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZTUaUBborPNJ90qX9pQc8Dg1axVt_rgA
"""

# -*- coding: utf-8 -*-
import time
from io import BytesIO
from datetime import datetime
from zoneinfo import ZoneInfo

import streamlit as st
import gspread
from gspread.exceptions import APIError, WorksheetNotFound
from streamlit_js_eval import streamlit_js_eval
from google.oauth2.service_account import Credentials

# ReportLab - PDF
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.graphics.barcode import qr
from reportlab.graphics.shapes import Drawing

# =====================
# CONFIGURAÇÕES
# =====================

SHEET_ID = "11JaCc4y-htBW-cxbvbMBV28GHYlORbMM6345TSaXcgQ"
NOME_ABA = "Respostas"

scope = [
    "https://www.googleapis.com/auth/spreadsheets",
    "https://www.googleapis.com/auth/drive",
]

# =====================
# GOOGLE SHEETS (credenciais)
# =====================

service_account_info = dict(st.secrets["gcp_service_account"])

credentials = Credentials.from_service_account_info(
    service_account_info,
    scopes=scope
)
gc = gspread.authorize(credentials)

# =====================
# FUNÇÕES AUXILIARES
# =====================

def get_worksheet(gc_client, sheet_id: str, tab_name: str):
    try:
        sh = gc_client.open_by_key(sheet_id)
    except APIError as e:
        st.error("❌ Não foi possível abrir a planilha. Verifique permissões e o ID.")
        st.stop()
    try:
        ws = sh.worksheet(tab_name)
    except WorksheetNotFound:
        st.error(f"❌ A aba '{tab_name}' não existe na planilha.")
        st.stop()
    return ws

def append_with_retry(ws, row, retries=4):
    for i in range(retries):
        try:
            ws.append_row(row)
            return True
        except APIError as e:
            code = getattr(getattr(e, "response", None), "status_code", None)
            if code in (429, 500, 503) and i < retries - 1:
                time.sleep((2 ** i) + 0.1)
                continue
            raise

# =====================
# FUNÇÃO PARA GERAR PDF
# =====================

def gerar_pdf_checklist(
    agora, regional, coordenador, loja, supervisor,
    latitude, longitude, precisao,
    perguntas, respostas
):
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4)

    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(name="Titulo", fontSize=16, leading=18))
    styles.add(ParagraphStyle(name="Sub", fontSize=12, leading=14))
    styles.add(ParagraphStyle(name="Normal10", fontSize=10, leading=12))

    elementos = []

    elementos.append(Paragraph("Check-list de Acompanhamento", styles["Titulo"]))
    elementos.append(Paragraph("Identificação", styles["Sub"]))

    meta = [
        ["Data/Hora", agora],
        ["Regional", regional],
        ["Coordenador", coordenador],
        ["Loja", loja],
        ["Supervisor", supervisor],
        ["Latitude", latitude],
        ["Longitude", longitude],
        ["Precisão", precisao],
    ]
    tabela = Table(meta, colWidths=[80, 300])
    tabela.setStyle(TableStyle([("GRID", (0,0), (-1,-1), 0.5, colors.grey)]))
    elementos.append(tabela)
    elementos.append(Spacer(1, 12))

    elementos.append(Paragraph("Perguntas e Respostas", styles["Sub"]))

    linhas = [["#", "Pergunta", "Resposta"]]
    for i, (p, r) in enumerate(zip(perguntas, respostas), start=1):
        linhas.append([str(i), p, r])

    tabela2 = Table(linhas, colWidths=[20, 380, 80])
    tabela2.setStyle(TableStyle([
        ("GRID", (0,0), (-1,-1), 0.5, colors.grey),
        ("BACKGROUND", (0,0), (-1,0), colors.lightgrey),
    ]))
    elementos.append(tabela2)
    elementos.append(Spacer(1, 12))

    doc.build(elementos)
    buffer.seek(0)
    return buffer
