# -*- coding: utf-8 -*-
"""Planilha.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZTUaUBborPNJ90qX9pQc8Dg1axVt_rgA
"""

import streamlit as st
import gspread
from google.oauth2.service_account import Credentials

scope = [
    "https://www.googleapis.com/auth/spreadsheets",
    "https://www.googleapis.com/auth/drive"
]

# 🔑 Converter secrets para dict normal
service_account_info = dict(st.secrets["gcp_service_account"])

# 🔥 Corrigir quebras de linha da chave privada
service_account_info["private_key"] = service_account_info["private_key"].replace("\\n", "\n")

credentials = Credentials.from_service_account_info(
    service_account_info,
    scopes=scope
)

gc = gspread.authorize(credentials)

st.success("Service Account conectada com sucesso 🎉")

